### PR TITLE
Fix invalid paths in management rest API

### PR DESCRIPTION
**Pull request by Andy2003**
This PR fixes the invalid paths in the swagger definition of the management rest API

### CODE REVIEW

**Comment by aelamrani** [comment]
Hi @Andy2003 

Please explain the purpose of this pull request. Is it just about a conversion from yaml to json?

**Comment by Andy2003** [comment]
1. Invalid paths were used:
1.1. /notifiers
1.2. /notifiers/{notifier}/schema
1.3. /notifiers/{notifier}
2. In version 3.2. the paths were prefixed with `/organizations/{orgId}` or `/organizations/{orgId}/environments/{envId}`, but both `orgId` and `envId` were missing in the parameter definition. This PR adds them.

Btw.: I made 2 commits to this PR the 1st ist the conversion into `yaml`, the 2nd is the actual fix of the path parameters.

**Comment by aelamrani** [comment]
Ok I got you. So for the management API we are generating the descriptor from the code with annotations. So I would prefer to fix this in the code and use the generated json there. What do you think?

**Comment by Andy2003** [comment]
Would be much better, as long as the generated definition is valid.

**Comment by Andy2003** [comment]
If the definition can be retrieved from a running instance, we should also add the path to download the definition into the docs.

**Comment by aelamrani** [comment]
Agree. So waiting for your PRs and closing this one.

Thanks

**Comment by Andy2003** [comment]
@aelamrani can you please explain me how you currently generate the swagger.json? Is there an endpoint I can invoke to get the current description?

**Comment by aelamrani** [comment]
It is generated at your_api_url/management/swagger.json

For example here: https://nightly.gravitee.io/api/management/swagger.json

**Pull request closed without merging**
