### PR TITLE
feat(oauth2) : add oauth2 authentication documentation

### PR DESCRIPTION
**Pull request by tcompiegne**
Complete documentation for the oauth2 authentication mode for both Management REST API and Management Web UI.

This closes gravitee-io/issues#100

### CODE REVIEW

**Comment by NicolasGeraud** [comment]
Please add an issue in gravitee-io/issues and reference it in your commit message.

**Comment by tcompiegne** [comment]
@NicolasGeraud done !

**Comment by NicolasGeraud** [comment]
you have to link the commit to the issue by adding keywords on your commit message, not on your PR message.

Could you add `fix gravitee-io/issues#100`on your commit message ?

This way, all your PR will be linked to your issue and be grouped on waffle.

thx

**Comment by tcompiegne** [comment]
No more accurate since social connect

**Pull request closed without merging**
