### PR TITLE
Doc 22

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

https://graviteedevops.atlassian.net/browse/DOC-22

**Description**
fix curl exemple on subscribe to api request

**Screenshots**

**Additional context**

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://graviteedocs.blob.core.windows.net/doc-22/index.html)

### CODE REVIEW

**Review by gaetanmaisse — APPROVED** [review]

**Review by ivan-gravitee — APPROVED** [review]

**Comment by ivan-gravitee** [comment]
Hey @ThibaudAV  just a note that AFAIK we don't use the `develop` branch anymore so perhaps redirect the PR to `master`. @gaetanmaisse can you confirm please?

**Comment by gaetanmaisse** [comment]
Confirmed! Well spotted @ivan-gravitee

**Comment by ThibaudAV** [comment]
could we remove develop branches ?

**Comment by ivan-gravitee** [comment]
> could we remove develop branches ?

I'm definitely up for that - @gaetanmaisse @lju-lazarevic (add others), any objections?

**Pull request merged**
