### PR TITLE
docs(cert): support for auto reload certificate when updated

### PR DESCRIPTION
**Pull request by jhaeyaert**
**Issue**

gravitee-io/issues#5888

**Description**

Document the ability to configure gateway keystore (to enable SSL) using either file or kubernetes (secret or configmap)

### CODE REVIEW

**Review by plsstephenson — APPROVED** [review]
Changes made - please check

**Comment by brasseld** [comment]
> hanges made - please check

LGTM @plsstephenson 

Can you please merge ?

**Comment by mouligno** [comment]
@plsstephenson can you merge this on master so it's available ?

**Comment by plsstephenson** [comment]
I can do this tomorrow. If you need it sooner, please ask Sion.

**Pull request merged**
